### PR TITLE
Various enhancements

### PR DESCRIPTION
**Pull request by lukecyca**
- Added function pattern so each diffed file shows in the function menu.
- Added keyword highlighting.
- Fixed a bug which prevented highlighting empty lines added or removed.

### CODE REVIEW

**Comment by rwilcox** [comment]
AWWWWEEESOMME!!!! I'll play around with this later tonigh!!!!!!!

**Comment by rwilcox** [comment]
Very cool - I like your improvements especially with the keyword stuff.

However, the function popup feature (what I was really looking forward to) doesn't work for me.

I tried viewing a diff from git (using git show SHA1 in a commit that touched multiple files). The diff highlighted correctly, but the functions didn't work.

I don't follow enough of your function matching regex to fix this myself, but I did take some samples of some of the lines that I think you were trying to match, and have included them below.

OTOH, if everything works for you, maybe I need to debug stuff on my end (or maybe you were trying with diffs from one thing, and I'm trying with diffs from another).

 From `git show`:

```
diff --git a/src/transports/http.c b/src/transports/http.c
index ce68ab7..38446bd 100644
--- a/src/transports/http.c
+++ b/src/transports/http.c
```

From `diff -u` on the command line:

```
--- diff.plist  2012-01-27 14:08:14.000000000 -0500
+++ ../bbedit_rails_filters/rails_emacs_mode.rb 2011-11-27 12:14:59.000000000 -0500
```

Not really sure which you were trying to match (both would be awesome - I'm eyeballing moving your changes over to the Git BBEdit Package's Diff language module too... so the git style support would be cool :-) 

Thanks!!

**Comment by lukecyca** [comment]
I made the regexp match the particular diffs I view most often, which are the ones from Mercurial Patch Queues.  I'll see if I can also get it working for those other varieties.

What I would really love (and what I initially set out to accomplish) is to be able to colour the added/removed lines in a higher contrast colour.  TextMate's built-in Diff syntax colouring is great (see a screenshot on http://metaskills.net/2005/12/22/textmate-by-programmers-for-efficiency-experts/).

**Comment by rwilcox** [comment]
> What I would really love (and what I initially set out to accomplish) is to be able to colour the added/removed lines
> in a higher contrast colour

Agreed. BBEdit's syntax coloring/customizing support is waaay behind what was possible in TextMate. I just had to pick areas that were _probably_ differently colored (I keep my comments a light gray, and strings a bolder color), but it's pretty much just hail mary. :-(

**Pull request closed without merging**
